#!/bin/sh

set -e

case "$1" in
  purge|remove)
    if [ -e /opt/copy-client ]; then
      rm -rf /opt/copy-client
    fi
    if [ -e /lib/copy ]; then
      rm -rf /lib/copy
    fi
  ;;

esac



exit 0
