#!/bin/sh

set -e

case "$1" in

  configure)
    cd /opt/copy-client/
    tar -xvf copy.tar.gz
    rm -r copy.tar.gz
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac



exit 0
