#!/bin/sh

set -e

case "$1" in
  purge|remove)
    if [ -e /opt/copy-client ]; then
      rm -rf /opt/copy-client
    fi
    if [ -e /lib/copy ]; then
      rm -rf /lib/copy
    fi
  ;;

esac

# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/ubuntu-mono-dark /usr/share/icons/ubuntu-mono-light
fi
# End automatically added section


exit 0
