#!/bin/sh

set -e

case "$1" in

  configure)
    cd /opt/copy-client/
    tar -xvf copy.tar.gz
    rm -r copy.tar.gz
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/ubuntu-mono-dark /usr/share/icons/ubuntu-mono-light
fi
# End automatically added section


exit 0
